name: Docker

on:
  push:
    branches:
      - 'alarm'

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SHAIRPORT_SYNC_VERSION: 4.3.5
      NQPTP_BRANCH: main
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3.5.2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          platforms: linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/amd64
          build-args: |
            SHAIRPORT_SYNC_BRANCH=${{ env.SHAIRPORT_SYNC_VERSION }}
            NQPTP_BRANCH=${{ env.NQPTP_BRANCH }}
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shairport-sync-alarm:${{ env.SHAIRPORT_SYNC_VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/shairport-sync-alarm:latest
